/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PCService;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author msi
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        Image();
    }

    private void Image()
    {
        Icon i = lblBG.getIcon();
        ImageIcon icon = (ImageIcon)i;
        Image scale = icon.getImage().getScaledInstance(lblBG.getWidth(),lblBG.getHeight(),Image.SCALE_SMOOTH);
        lblBG.setIcon(new ImageIcon(scale));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTCreate = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTUpdate = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MAIN MENU");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,100));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTCreate.setFont(new java.awt.Font("U4 Brothers. 00025", 1, 28)); // NOI18N
        lblTCreate.setForeground(new java.awt.Color(255, 255, 255));
        lblTCreate.setText("  TABLE CREATE");
        lblTCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTCreateMouseClicked(evt);
            }
        });
        jPanel1.add(lblTCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 220, 50));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,100));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTUpdate.setFont(new java.awt.Font("U4 Brothers. 00025", 1, 28)); // NOI18N
        lblTUpdate.setForeground(new java.awt.Color(255, 255, 255));
        lblTUpdate.setText(" TABLE UPDATE");
        lblTUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTUpdateMouseClicked(evt);
            }
        });
        jPanel2.add(lblTUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 220, 50));

        jButton1.setBackground(new java.awt.Color(255, 51, 255));
        jButton1.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOG OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 150, 30));

        lblBG.setIcon(new javax.swing.ImageIcon("C:\\project\\pc2.jpg")); // NOI18N
        getContentPane().add(lblBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
       
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        TableUpdate tu = new TableUpdate();
        this.setVisible(false);
        tu.setVisible(true);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void lblTCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTCreateMouseClicked
        TableCreate tc = new TableCreate();
        this.setVisible(false);
        tc.setVisible(true);
    }//GEN-LAST:event_lblTCreateMouseClicked

    private void lblTUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTUpdateMouseClicked
        TableUpdate tu = new TableUpdate();
        this.setVisible(false);
        tu.setVisible(true);
    }//GEN-LAST:event_lblTUpdateMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int dialog = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To LOG OUT?","Warning",JOptionPane.YES_NO_OPTION);
        if(dialog==JOptionPane.YES_OPTION)
        {
        LoginForm lg = new LoginForm();
        this.setVisible(false);
        lg.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBG;
    private javax.swing.JLabel lblTCreate;
    private javax.swing.JLabel lblTUpdate;
    // End of variables declaration//GEN-END:variables
}
